name: 'Update Version'

on:
  push:
    tags: [ 'mkrel-[0-9]+.[0-9]+.[0-9]+-?**' ]
  workflow_dispatch:

defaults:
  run:
    shell:  |
            pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"

jobs:
  # This job is required because C# is assholes and dotnet publish refuses to use the version number set by the SetVersion.ps1 script.
  update-version-number:
    runs-on:  windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref:          'main'
          fetch-depth:  0

      - name:   Update .csproj Version Numbers
        id:     update-version
        run:    |
                $( git describe --tags --abbrev=0) -match 'mkrel-(.+)' > $null
                $tag = $matches[1]
                if ( "$tag" -eq "" ) { echo "FAILED TO GET TAG" ; exit 1 }
                $tag -cmatch '(?<MAJOR>\d+?)\.(?<MINOR>\d+?)\.(?<PATCH>\d+?)(?<EXTRA>.*)' > $null
                $tag_3_part = $Matches.MAJOR + '.' + $Matches.MINOR + '.' + $Matches.PATCH
                $copyright = "Copyright © 2022-$((Get-Date).Year) by `$`(Authors`)"
                
                .\.github\workflows\scripts\SetProperty.ps1  -Path WpfExporter/WpfExporter.csproj  "Version=$tag"  "FileVersion=$tag_3_part"  "Copyright=$copyright"

                echo "tag=$tag" >> "$GITHUB_OUTPUT"
                if ("$tag" -eq "") { exit 1 }

      - name:   Push Changes
        run:    |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add -A
                git commit -m "Update .csproj Version Numbers"
                git push origin

      - name:   Create & Push Tag
        uses:   actions-ecosystem/action-push-tag@v1.0.0
        with:
          tag: "${{ steps.update-version.outputs.tag }}"
          message: "Tag for version ${{ steps.update-version.outputs.tag }} generated by the UpdateVersion.yaml workflow"

      - name:   "Repo Dispatch 'make-release'"
        uses:   peter-evans/repository-dispatch@v2.1.2
        with:
          event-type: make-release
          client-payload: |-
            {
              "ref": "${{ github.ref }}",
              "tag": "${{ steps.update-version.outputs.tag }}"
            }
        
# HEAD:github-actions
